apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: robot-platform
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: grabber-platform
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: api-gateway
  type: ClusterIP
