apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: robot-platform
  labels:
    app: auth-service
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: grabber-platform
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "mysql"
  DB_NAME: "auth_db"
  DB_USER: "auth_user"
