apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: robot-platform
  labels:
    app: ai-service
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: grabber-platform
spec:
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  selector:
    app: ai-service
  type: ClusterIP
