apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: robot-platform
  labels:
    app: mqtt
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/part-of: grabber-platform
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    
    # Log configuration
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    
    # TCP Listener (Internal)
    listener 1883 0.0.0.0
    allow_anonymous false
    password_file /mosquitto/config/pwfile
    
    # WebSocket Listener (External Exposure)
    listener 9001 0.0.0.0
    protocol websockets
    allow_anonymous false
    password_file /mosquitto/config/pwfile
