apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data-pvc
  namespace: robot-platform
  labels:
    app: mqtt
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/part-of: grabber-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
