apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: robot-platform
  labels:
    app: mqtt
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/part-of: grabber-platform
spec:
  ports:
    - name: mqtt-tcp
      port: 1883
      targetPort: 1883
    - name: mqtt-ws
      port: 9001
      targetPort: 9001
  selector:
    app: mqtt
  type: ClusterIP
