apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: robot-platform
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    protected-mode yes
    port 6379
    dir /data
