apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: robot-platform
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: grabber-platform
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
