apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
type: Opaque
stringData:
  tunnel-token: "eyJhIjoiY2QzZjZkNWYwMGZiM2NmYmFiNmQ2NmNhZTkyYWM5NTUiLCJ0IjoiNzFiMGI1NDctZjgxZi00ODNlLTk5MjEtZTFkYmU5MzgzYTc5IiwicyI6Ik9HUXpNMkV5TkdFdFpUZGhNeTAwTkdFMUxUaG1OR1V0WVdGbU1USTBZVGhqTnpJMSJ9"
